Repository Pyxsys/SOEN390_19, pull requests merged in 2021-04, with the labels that each got.

#99 Config #93
  Client/src/APIService.js
  Client/src/Components/Inventory/InventorySideBar/Parts.js
  Client/src/Components/Inventory/InventorySideBar/useAddInventory.js
  Client/src/Components/Inventory/InventorySideBar/usePartsForm.js
  Client/src/Components/Manufacturing/useManufacturingForm.js
  Client/src/Forms/useForm.js
  Client/src/Forms/useLogin.js
  Client/src/config.json
Labels: front-end

#103 Netfly deploy
  .gitignore
  Client/src/config.json
  README.md
  Server/Procfile
  Server/package.json
  Server/src/app.js
  Server/src/seed.js
Labels: back-end, build, environment, front-end

#107 Css final fixes
  Client/src/CSSFiles/Manufacturing.css
  Client/src/Components/Manufacturing/ManufacturingForm.js
Labels: front-end

#108 Final testing
  Server/__tests__/Accounting.test.js
  Server/__tests__/Assembler.test.js
  Server/package.json
Labels: test
