Repository Pyxsys/SOEN390_19, pull requests merged in 2021-03, with the labels that each got.

#72 Assembler model
  Server/package-lock.json
  Server/src/Models/Assembler.js
Labels: back-end

#75 Back-end assembly feature added
  Server/package-lock.json
  Server/src/Models/Assembler.js
  Server/src/app.js
  Server/src/seed.js
Labels: back-end, feature, inventory, production

#71 Fixed json and added react component for navbar
  Client/package-lock.json
  Client/src/Components/Manufacturing/Manufacturing.js
  Client/src/Components/Navbar/MenuItems.js
  Client/src/Components/OnceLoggedIn.js
  Server/package-lock.json
Labels: front-end

#84 Travis introduction
  .gitignore
  .travis.yml
  Server/__tests__/Bike.test.js
  Server/__tests__/BikePart.test.js
  Server/__tests__/Business.test.js
  Server/__tests__/Client.test.js
  Server/__tests__/Supplier.test.js
  Server/__tests__/User.test.js
  Server/package-lock.json
  Server/package.json
Labels: back-end, tracking

#85 Fe header
  Client/src/APIService.js
  Client/src/App.js
  Client/src/Components/Inventory/InventorySideBar/AddInventoryForm.js
  Client/src/Components/Inventory/InventorySideBar/Inventory.js
  Client/src/Components/Inventory/InventorySideBar/InventoryHome.js
  Client/src/Components/Inventory/InventorySideBar/InventorySideBar.js
  Client/src/Components/Inventory/InventorySideBar/InventorySideBarData.js
  Client/src/Components/Inventory/InventorySideBar/Parts.js
  Client/src/Components/Inventory/InventorySideBar/useAddInventory.js
  Client/src/Components/Manufacturing/Manufacturing.js
  Client/src/Components/Navbar/MenuItems.js
  Client/src/Components/Navbar/NavBarButton.js
  Client/src/Components/Navbar/Navbar.js
  Client/src/Components/OnceLoggedIn.js
  Client/src/Components/Routes.js
  Client/src/Components/SignUpAndSuccessPage.js
  Client/src/Contexts/AuthorizationContext.js
  Client/src/Forms/FormLogin.js
  Client/src/Forms/FormSignUp.js
  Client/src/Forms/FormSuccess.js
  Client/src/Forms/useForm.js
  Client/src/Forms/useLogin.js
  Client/src/Forms/validateInfo.js
  Client/src/Forms/validateLogin.js
  Client/src/index.js
Labels: documentation, front-end, refactor

#81 Patch 58 fixes "Provideer" typo
  Client/package-lock.json
  Client/src/Components/Inventory/InventorySideBar/Parts.js
Labels: bug, front-end

#86 Middleware_50 into BE_PreProd
  Server/src/Middleware/Logger.js
  Server/src/app.js
Labels: back-end

#88 Front end draft
  Client/src/CSSFiles/Form.css
  Client/src/CSSFiles/InventoryHome.css
  Client/src/CSSFiles/Navbar.css
  Client/src/Components/Inventory/InventorySideBar/AddInventoryForm.js
  Client/src/Components/Inventory/InventorySideBar/InventoryHome.js
  Client/src/Components/Inventory/InventorySideBar/Parts.js
  Client/src/Components/Inventory/InventorySideBar/PartsForm.js
  Client/src/Components/Inventory/InventorySideBar/useAddInventory.js
  Client/src/Components/Inventory/InventorySideBar/usePartsForm.js
  Client/src/Components/Manufacturing/Manufacturing.js
  Client/src/Components/Manufacturing/ManufacturingForm.js
  Client/src/Components/Manufacturing/ManufacturingHome.js
  Client/src/Components/Manufacturing/useManufacturingForm.js
  Client/src/Components/Navbar/MenuItems.js
  Client/src/Components/OnceLoggedIn.js
  Server/__tests__/Assembler.test.js
  Server/__tests__/Bike.test.js
  Server/src/Models/Assembler.js
  Server/src/Models/Bike.js
  Server/src/Models/BikePart.js
  Server/src/Models/Business.js
  Server/src/Models/Supplier.js
  Server/src/Models/User.js
  Server/src/Routes/Api/InventoryRoutes.js
  Server/src/Routes/Api/ManufacturingRoutes.js
  Server/src/Routes/Api/UserRoutes.js
  Server/src/app.js
  Server/src/seed.js
Labels: back-end, design, feature, front-end, inventory, production

#90 quashing the return of hotfix
  Server/src/Models/Assembler.js
Labels: bug
