Repository Pyxsys/SOEN390_19, pull requests merged in 2021-02, with the labels that each got.

#41 Pass encrypt feature
  Server/package-lock.json
  Server/package.json
  Server/src/Controllers/UserController.js
  Server/src/Models/User.js
  Server/src/Routes/Api/UserRoutes.js
  Server/src/app.js
Labels: back-end, feature

#45 Business model
  .gitignore
  Client/.eslintcache
  Server/package-lock.json
  Server/package.json
  Server/src/Models/Business.js
  Server/src/Models/Client.js
  Server/src/Models/Supplier.js
  package-lock.json
  src/View/package-lock.json
Labels: back-end

#46 Pyxsys inv models 34
  README.md
  Server/src/Models/Bike.js
  Server/src/Models/BikePart.js
Labels: back-end, documentation

#48 Inv routes 37
  .gitignore
  Data/BikeParts/null.dummy
  Data/Bikes/null.dummy
  Data/README.md
  Server/package-lock.json
  Server/package.json
  Server/src/Models/Bike.js
  Server/src/Models/BikePart.js
  Server/src/Models/Business.js
  Server/src/Models/Client.js
  Server/src/Models/Supplier.js
  Server/src/Routes/Api/InventoryRoutes.js
  Server/src/app.js
  package-lock.json
Labels: back-end, feature

#49 Dummy data 39
  README.md
  Server/src/Routes/Api/InventoryRoutes.js
  Server/src/app.js
  Server/src/seed.js
  package-lock.json
Labels: back-end, documentation, feature

#53 Unit testing
  Server/__tests__/Bike.test.js
  Server/__tests__/BikePart.test.js
  Server/__tests__/Business.test.js
  Server/__tests__/Client.test.js
  Server/__tests__/Supplier.test.js
  Server/__tests__/User.test.js
  Server/package-lock.json
  Server/package.json
  Server/src/app.js
Labels: back-end, test

#54 Michael's branch
  Client/package-lock.json
  Client/package.json
  Client/src/APIService.js
  Client/src/App.js
  Client/src/CSSFiles/InventoryHome.css
  Client/src/CSSFiles/Navbar.css
  Client/src/CSSFiles/SideBars.css
  Client/src/Components/Inventory/InventorySideBar/AddInventoryForm.js
  Client/src/Components/Inventory/InventorySideBar/Inventory.js
  Client/src/Components/Inventory/InventorySideBar/InventoryHome.js
  Client/src/Components/Inventory/InventorySideBar/InventorySideBar.js
  Client/src/Components/Inventory/InventorySideBar/InventorySideBarData.js
  Client/src/Components/Inventory/InventorySideBar/Parts.js
  Client/src/Components/Inventory/InventorySideBar/useAddInventory.js
  Client/src/Components/Navbar/MenuItems.js
  Client/src/Components/Navbar/NavBarButton.js
  Client/src/Components/Navbar/Navbar.js
  Client/src/Components/OnceLoggedIn.js
  Client/src/Components/Routes.js
  Client/src/Components/SignUpAndSuccessPage.js
  Client/src/Contexts/AuthorizationContext.js
  Client/src/Forms/FormLogin.js
  Client/src/Forms/FormSignUp.js
  Client/src/Forms/FormSuccess.js
  Client/src/Forms/useForm.js
  Client/src/Forms/useLogin.js
  Client/src/Forms/validateInfo.js
  Client/src/Forms/validateLogin.js
  Server/src/Routes/Api/InventoryRoutes.js
Labels: front-end, inventory
